version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.20.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go install github.com/ActiveState/gozip/cmd/gozip@e455986
            wget https://platform.activestate.com/dl/cli/_pdli01/install.sh
            chmod +x install.sh
            export VERBOSE=true
            env
            ./install.sh -b mitchell/dx-1634 --force -t /tmp/activestate
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build
          command: /tmp/activestate/bin/state run build-test
      - run:
          name: Run tests
          command: go test github.com/ActiveState/offline-installer/test/integration
workflows:
  version: 2
  test:
    jobs:
      - test
